//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("g7SF+Qlr5FV1MzxnBqERqFjGwf/U55hRDNAhH61N09MpYZ5bIq2xmLOqNjRePEO1KYcD+ciBtpflZxELE" +
            "gZWB7MYvLv67O2u99yeYkSPUHTX1wwgqexKAzf2EwkziqtYxoEeIalkXuOZ5pdbmM/cowdB04t89/1O/" +
            "w1cDnyilFU=")]
        public string ChannelAccessToken {
            get {
                return ((string)(this["ChannelAccessToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("874482658d306937c907d0c4d9ab3bd9")]
        public string ChannelSecret {
            get {
                return ((string)(this["ChannelSecret"]));
            }
        }
    }
}
